name: Develop
on:
  push:
    branches:
      - develop

jobs:
  install:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright/
            ~\AppData\Local\ms-playwright\
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  build:
    name: Build
    needs: semantic-version
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright/
            ~\AppData\Local\ms-playwright\
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Build
        run: |
          npm run static --build-analyze --base=/UnfilteredTruth/ --website-host=https://grabarzundpartner.github.io/UnfilteredTruth
          mkdir dist/reports dist/reports/webpack
          cp -R .reports/webpack/* dist/reports/webpack
          touch dist/.nojekyll
        env:
          DIST_PATH: dist
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: artifact
          path: dist

  deploy-ghpages:
    name: Deploy (GH-Pages)
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - name: Download Artifact (Docs)
        uses: actions/download-artifact@master
        with:
          name: artifact
          path: public
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
